name: Save Notes

on:
  push:
    paths:
      - 'notes/**'

permissions:
  contents: write

jobs:
  process-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create notes directory
        run: |
          mkdir -p notes
          touch notes/.gitkeep

      - name: Commit and push
        run: |
          git add notes/
          git commit -m "Initialize notes directory" || echo "No changes to commit"
          git push