name: Update Notes

on:
  repository_dispatch:
    types: [update_notes]
  workflow_dispatch: # Allow manual trigger
  push:
    paths-ignore:
      - 'notes.json'

permissions:
  contents: write

jobs:
  update-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update notes.json
        run: |
          echo '${{ toJson(github.event.client_payload.notes) }}' > notes.json

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add notes.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update notes" && git push)